//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMonitor) DeepCopyInto(out *DeploymentMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMonitor.
func (in *DeploymentMonitor) DeepCopy() *DeploymentMonitor {
	if in == nil {
		return nil
	}
	out := new(DeploymentMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMonitorList) DeepCopyInto(out *DeploymentMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMonitorList.
func (in *DeploymentMonitorList) DeepCopy() *DeploymentMonitorList {
	if in == nil {
		return nil
	}
	out := new(DeploymentMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMonitorSpec) DeepCopyInto(out *DeploymentMonitorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMonitorSpec.
func (in *DeploymentMonitorSpec) DeepCopy() *DeploymentMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMonitorStatus) DeepCopyInto(out *DeploymentMonitorStatus) {
	*out = *in
	if in.LastNotificationTime != nil {
		in, out := &in.LastNotificationTime, &out.LastNotificationTime
		*out = (*in).DeepCopy()
	}
	if in.LastNotifiedDeploymentMap != nil {
		in, out := &in.LastNotifiedDeploymentMap, &out.LastNotifiedDeploymentMap
		*out = make(map[string]DeploymentState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMonitorStatus.
func (in *DeploymentMonitorStatus) DeepCopy() *DeploymentMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentState) DeepCopyInto(out *DeploymentState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentState.
func (in *DeploymentState) DeepCopy() *DeploymentState {
	if in == nil {
		return nil
	}
	out := new(DeploymentState)
	in.DeepCopyInto(out)
	return out
}
